FROM trinodb/trino:451

USER root

COPY resources/ranger-2.3.0-trino-plugin.tar /root/ranger-2.3.0-trino-plugin.tar

RUN cd /root && \
    tar xvf ranger-2.3.0-trino-plugin.tar

COPY resources/install.properties /root/ranger-2.3.0-trino-plugin/install.properties
COPY resources/enable-trino-plugin.sh /root/ranger-2.3.0-trino-plugin/enable-trino-plugin.sh

RUN cd /root && \
    chown root:root -R /root/ranger-2.3.0-trino-plugin/* && \
    /root/ranger-2.3.0-trino-plugin/enable-trino-plugin.sh