# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: "keycloak-sandbox-test"

ingress:
  enabled: true
  className: nginx-internal
  host: keycloak-sandbox-test.stage-data.nb-stage.com