# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: "keycloak-sandbox-test"

environment:
  log_level: "DEBUG"

configmap:
  enabled: false

server:
  autoscale:
    enabled: false
    keda:
      enabled: false

  podDisruptionBudget:
    enabled: false

  annotations:
    prometheus.io/scrape: 'false'

  image:
    repository: quay.io/keycloak/keycloak
    tag: "9.0.2"
    pullPolicy: Always

  podSecurityContext: {}

  minReadySeconds: 15
  terminationGracePeriodSeconds: 60
  deploymentStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0

  env:
    - name: SERVER_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: KEYCLOAK_USER
      value: admin
    - name: KEYCLOAK_PASSWORD
      value: admin

  env_extra: []

  resources:
    limits:
      cpu: 2000m
      memory: 4000Mi
    requests:
      cpu: 1000m
      memory: 4000Mi

  ports:
    - name: http
      containerPort: 8080
      protocol: TCP

  livenessProbe:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 15
    periodSeconds: 10
    failureThreshold: 60

  readinessProbe:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 15
    periodSeconds: 10

  nodeSelector: {}

  tolerations: []

  affinity: {}

  sidecarContainers: {}

service:
  type: ClusterIP
  port: 80
  containerPort: 8080

ingress:
  enabled: true
  className: nginx-internal
  host: keycloak-sandbox-test.sandbox-dev-first.nb-sandbox.com