# Default values for ads-api-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: "ranger-stage-test"

environment:
  log_level: "DEBUG"

configmap:
  enabled: false

server:
  autoscale:
    enabled: false
    keda:
      enabled: false

  podDisruptionBudget:
    enabled: false

  annotations:
    prometheus.io/scrape: 'false'

  image:
    repository: registry.n.newsbreak.com/apache/ranger
    tag: 3.0.0-SNAPSHOT-amd64
    pullPolicy: Always

  podSecurityContext: {}

  minReadySeconds: 15
  terminationGracePeriodSeconds: 60
  deploymentStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0

  env:
    - name: SERVER_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP

  env_extra: []

  command: ["/root/docker-entrypoint.sh"]

  resources:
    limits:
      cpu: 4000m
      memory: 8000Mi
    requests:
      cpu: 3000m
      memory: 8000Mi

  ports:
    - name: http
      containerPort: 6080
      protocol: TCP

  livenessProbe:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 15
    periodSeconds: 10
    failureThreshold: 60

  readinessProbe:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 15
    periodSeconds: 10

  nodeSelector: {}

  tolerations: []

  affinity: {}

  sidecarContainers: {}

service:
  type: ClusterIP
  port: 80
  containerPort: 6080

ingress:
  enabled: false
