# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: "hue-stage-test"

environment:
  log_level: "DEBUG"

configmap:
  enabled: false

server:
  autoscale:
    enabled: false
    keda:
      enabled: false

  podDisruptionBudget:
    enabled: false

  annotations:
    prometheus.io/scrape: 'false'

  image:
    repository: registry.n.newsbreak.com/hue-with-oidc
    tag: 20240716-140101
    pullPolicy: Always

  podSecurityContext: {}

  minReadySeconds: 15
  terminationGracePeriodSeconds: 60
  deploymentStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0

  env:
    - name: SERVER_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP

  env_extra: []

  resources:
    limits:
      cpu: 2000m
      memory: 4000Mi
    requests:
      cpu: 1000m
      memory: 4000Mi

  ports:
    - name: http
      containerPort: 8888
      protocol: TCP

  livenessProbe:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 15
    periodSeconds: 10
    failureThreshold: 60

  readinessProbe:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 15
    periodSeconds: 10

  nodeSelector: {}

  tolerations: []

  affinity: {}

  sidecarContainers: []

service:
  type: ClusterIP
  port: 80
  containerPort: 8888

ingress:
  enabled: false